### ISSUE TITLE
release this extension for firefox please, thanks

### ISSUE THREAD

**Issue by darkefsad** [ch1y0w0/ParamScan#1]
we need this extension for firefox.

**Comment by FeintBE** [comment]
Yes would be nice for firefox :) most bug bounters use firefox

**Comment by ch1y0w0** [comment]
It's already planned and in my todo list

**Comment by ya3raj** [comment]
Adding Extension on Firefox.

```
Open Firefox
Go to Settings>Extension&Themes
Click on settings icon and select DebugAdd-ons
Now click on Load Temporary Add on and load the folder you cloned from Github.
The Extension is Added.
```

![image](https://github.com/user-attachments/assets/4f81f5e8-112e-4bfd-8cc0-1760d0aaa0f3)

**Comment by ch1y0w0** [comment]
> Adding Extension on Firefox.
> 
> ```
> Open Firefox
> Go to Settings>Extension&Themes
> Click on settings icon and select DebugAdd-ons
> Now click on Load Temporary Add on and load the folder you cloned from Github.
> The Extension is Added.
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/59885197/392672274-4f81f5e8-112e-4bfd-8cc0-1760d0aaa0f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODkxODAsIm5iZiI6MTczMzM4ODg4MCwicGF0aCI6Ii81OTg4NTE5Ny8zOTI2NzIyNzQtNGY4MWY1ZTgtMTEyZS00YmZkLThjYzAtMTc2MGQwYWFhMGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4NTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MTgyNDU0NzczNTg4ZmYyZjdjYjYzY2E0OTFmZWY4MDdmYjllZmMyODdhY2Q4YTk3M2I1MTNjNWYzZmNiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7uSYO1oA4ezPrucxldCtS9gpXnu-UY_WzdOinUzMcRE)

Is it working probably for you? It's kinda buggy for me on firefox and i'm not sure if it's because the extension or firefox!?
![image](https://github.com/user-attachments/assets/96c108dd-8d95-4d9b-90bd-5820d7906c4f)

**Comment by ya3raj** [comment]
> > Adding Extension on Firefox.
> > ```
> > Open Firefox
> > Go to Settings>Extension&Themes
> > Click on settings icon and select DebugAdd-ons
> > Now click on Load Temporary Add on and load the folder you cloned from Github.
> > The Extension is Added.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/59885197/392672274-4f81f5e8-112e-4bfd-8cc0-1760d0aaa0f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODkxODAsIm5iZiI6MTczMzM4ODg4MCwicGF0aCI6Ii81OTg4NTE5Ny8zOTI2NzIyNzQtNGY4MWY1ZTgtMTEyZS00YmZkLThjYzAtMTc2MGQwYWFhMGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4NTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MTgyNDU0NzczNTg4ZmYyZjdjYjYzY2E0OTFmZWY4MDdmYjllZmMyODdhY2Q4YTk3M2I1MTNjNWYzZmNiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7uSYO1oA4ezPrucxldCtS9gpXnu-UY_WzdOinUzMcRE)
> 
> Is it working probably for you? It's kinda buggy for me on firefox and i'm not sure if it's because the extension or firefox!? ![image](https://private-user-images.githubusercontent.com/74054557/392732303-96c108dd-8d95-4d9b-90bd-5820d7906c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTA0MzQsIm5iZiI6MTczMzQxMDEzNCwicGF0aCI6Ii83NDA1NDU1Ny8zOTI3MzIzMDMtOTZjMTA4ZGQtOGQ5NS00ZDliLTkwYmQtNTgyMGQ3OTA2YzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0NDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMjZmNmZiODgxMzI0ODY1ZTI5OGUyNjg1YTBkMzcyMGEzZGFlMDM5NWQ4NTk5ZjNiZTAwMzBkZGZjNDE5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NCfSiGISX8NMzbZQMe9T-GohaK95HzYgPpfBCKuG6dQ)

yeah its a little buggy but it works anyhow :)

**Comment by FeintBE** [comment]
It works, but when a reflection is found, it does not show the full path url where it's found

**Comment by ch1y0w0** [comment]
I did some tweaking in commit 6057264. Please confirm if it's working normally on firefox
